#!/bin/sh 
#
# HA/FST - High Availability Cluster
# Copyright (C) 2003-2006 Reggie Beavers
# 
# Licensed under the terms of the GNU  General Public License:
# 		http://www.opensource.org/licenses/gpl-license.php
# 
# For further information visit:
# 		http://www.fstha.com/
# 
# File Name: fstdelvh
# 		Delete a virtual host
# 
# File Authors:
# 		Reggie Beavers (reggiebeavers@fstha.com)
#
#

BASE=`basename $0`
WARN=/tmp/$BASE.$$.w

usage () {
	echo " "
        echo "Usage: $BASE <OPTIONS>"
	echo " "
        echo "OPTIONS:"
	echo "       -v #    (txt, Virutal Host Number) REQUIRED or -V "
	echo "       -V str  (txt, Virutal Host Name)   REQUIRED or -v "
}

rm -f $WARN

# set defaults


while getopts :v:V: o
do
	case "$o" in
	v)	vhnumber="`expr 0 + $OPTARG`"
		res=$?
		if [ "$res" -gt 1 -o "$vhnumber" -lt 0 -o "$vhnumber" -gt 3 ]; then
			echo " "
			echo "v must be betwwen 0 and 3"
			exit 1
		fi
		;;
	V)	vhname="$OPTARG"
		if [ "x`$DIR\fstha export|grep lh.name|grep -w $vhname`" = "x" ]; then
			echo "$vhname could not be found"
			exit 1
		fi
		;;
	[?])    usage
		exit 1
		;;
	esac

done
shift `expr $OPTIND - 1`

if [ -f $WARN ]; then
	echo " "
	echo "Press [Return] to Continue  or  ^C "
	read foo
fi
rm -f $WARN


if [ "x$vhnumber" = "x" -a "x$vhname" = "x" ]; then
echo vhnumber=$vhnumber
echo vhname=$vhname
	usage
	exit 1
fi

if [ ! "x$vhname" = "x" ]; then
	vhnumber=`fstha export|grep "lh.name $vhname"|awk -F'h' '{print $2}'|awk -F'n' '{print $1}'`
	if [ $? -ne 0 ]; then
		echo "${BASE}: ERROR $vhname Not Found."
		usage
		exit 1
	fi
fi

echo "Working..."
fstha setfullq lh${vhnumber}name ""
fstha setfullq lh${vhnumber}node 9
fstha setfullq lh${vhnumber}stat 9
fstha setfullq lh${vhnumber}timeo 0
fstha setfullq lh${vhnumber}path ""
fstha setfullq lh${vhnumber}fallback 9
fstha setfullq lh${vhnumber}failto 9
echo "Done."
